### ISSUE TITLE
mac issues 

### ISSUE THREAD

**Issue by fkgruber** [Wainberg/ryp#3]
Hi
I'm running into several issues getting it to work in mac.
I installed it with pip  so I could use my existing R but once I get into the interactive R session C-d kills the session instead of going back to python

> >>> from ryp import r
> 
> >>> r("a=1")
> 
> >>> r("a")
> [1] 1
> >>> r()
> > a
> a
> [1] 1
> > 
> >>> 
> 
> Process mypy finished
> 

In fact any errors kills the session:

> > asdf
> asdf
> Error: object 'asdf' not found
> Execution halted
> 
> Process mypy exited abnormally with code 1

also trying to plot something with ggplot or base did not generate any plots

**Comment by fkgruber** [comment]
I tried creating a brand new conda environment with python 3.10 and when I try to plot I get:
```
conda create -n testryp python==3.10 pandas polars scipy pyarrow cffi -c conda-forge --verbose
pip install ryp
````

```
import pandas as pd
from ryp import r
r("a=1")

df=pd.DataFrame(
    {
        "x":[1,2,3,4,5,6],
        "y":[4,2,5,2,4,5]
    }
)

from ryp import to_r

to_r(df,"df")


r("""library(ggplot2)
     ggplot(df,aes(x,y))+
     geom_point()+
     geom_smooth(method="lm")
"""
  )
 
```
> > *** Terminating app due to uncaught exception
> 'NSInternalInconsistencyException', reason: 'nextEventMatchingMask
> should only be called from the Main Thread!'  *** First throw call
> stack: ( 0 CoreFoundation 0x00000001882922ec __exceptionPreprocess +
> 176 1 libobjc.A.dylib 0x0000000187d76158 objc_exception_throw + 60 2
> AppKit 0x000000018c271e2c -[NSApplication(NSEventRouting)
> _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 3096 3
> grDevices.so 0x0000000105ec1f1c input_handler + 156 4 libR.dylib
> 0x000000010616bbf0 R_runHandlers + 112 5 libffi.8.dylib
> 0x00000001054fc04c ffi_call_SYSV + 76 6 libffi.8.dylib
> 0x00000001054f974c ffi_call_int + 1208 7
> _cffi_backend.cpython-310-darwin.so 0x00000001054ca434 cdata_call +
> 1076 8 python3.10 0x0000000104dc1338 _PyObject_MakeTpCall + 332 9
> python3.10 0x0000000104ed04ec call_function + 732 10 python3.10
> 0x0000000104ecc574 _PyEval_EvalFrameDefault + 31656 11 python3.10
> 0x0000000104ec4184 _PyEval_Vector + 2588 12 python3.10
> 0x0000000104ecc85c _PyEval_EvalFrameDefault + 32400 13 python3.10
> 0x0000000104ec4184 _PyEval_Vector + 2588 14 python3.10
> 0x0000000104ed0454 call_function + 580 15 python3.10
> 0x0000000104ecc554 _PyEval_EvalFrameDefault + 31624 16 python3.10
> 0x0000000104ec4184 _PyEval_Vector + 2588 17 python3.10
> 0x0000000104ed0454 call_function + 580 18 python3.10
> 0x0000000104ecc554 _PyEval_EvalFrameDefault + 31624 19 python3.10
> 0x0000000104ec4184 _PyEval_Vector + 2588 20 python3.10
> 0x0000000104dc4d84 method_vectorcall + 336 21 python3.10
> 0x0000000104facd90 thread_run + 180 22 python3.10 0x0000000104f3f408
> pythread_wrapper + 48 23 libsystem_pthread.dylib 0x000000018813df94
> _pthread_start + 136 24 libsystem_pthread.dylib 0x0000000188138d34
> thread_start + 8 ) libc++abi: terminating due to uncaught exception of
> type NSException Abort trap: 6
> (testryp) fgruber@MS-CAM-033FA:~/Documents/general(bash-3.2)$

**Comment by Wainberg** [comment]
Thanks very much for reporting this! I use a Windows machine with WSL, so Mac testing was limited to running an automated test script that doesn't cover things like interactive plotting and Ctrl + D behavior. It does cover errors where the object isn't defined, so it's surprising that crashed for you. I'm setting up a Mac virtual machine now so I can see why it's not working on Mac like on Linux and Windows.

**Comment by fkgruber** [comment]
thanks. I'm upgrading homebrew libraries and see if it gets fixed. So far it works for me in both windows WSL and ubuntu.

**Comment by corrosive4354** [comment]
This error is usually related to threading issues in the graphical interface. You can try the following methods:
Make sure your R and Python environments are the latest versions, especially the ryp library.
Before drawing, make sure that R's graphics device has been started correctly. You can try to call dev.new() manually in R.
Try to run the code in different environments, such as in Jupyter Notebook or RStudio, to see if the same error occurs.

Also, seeing that you are using homebrew, I would like to recommend [Servbay](servbay.com) to you, which is more professional and easy to use on Mac than docker and homebrew

**Comment by Wainberg** [comment]
@fkgruber I set up the Mac VM and installed ryp through pip after installing the dependencies through conda/mamba, like you did. Ctrl + D works fine for me, and it doesn't crash when there's an error (nor did my automated testing on an actual Mac). 

Are you doing anything custom that might explain why it's breaking? I noticed you're running it with mypy, for example. 

I am getting a segfault when plotting. I'll look into that next.

**Comment by Wainberg** [comment]
@fkgruber I just pushed a fix for the Mac plotting issue. Everything's working fine on my end, but I'm curious to know what's causing your kill-on-Ctrl-D-and-errors bug. You mention you're using an existing R installation; what happens if you use one installed through conda in a clean environment?

**Comment by Wainberg** [comment]
Both ways are working fine on my end after the fix. Did you install the latest development version with `pip install git+https://github.com/Wainberg/ryp`?

**Comment by fkgruber** [comment]
yes. I can see the improvements. before I couldn't get plotting after going to r(). Now it works. It is weird that r("R code") crashes. seems like they should be practically equivalent

**Comment by Wainberg** [comment]
This works on my end:

```bash
conda create -n testryp python==3.10 pandas polars scipy pyarrow cffi -c conda-forge --verbose
conda activate testryp
pip install git+https://github.com/Wainberg/ryp
```

```python
import pandas as pd
from ryp import r, to_r

df = pd.DataFrame({"x":[1,2,3,4,5,6], "y":[4,2,5,2,4,5]})
to_r(df, "df")
r("""library(ggplot2)
     ggplot(df,aes(x,y))+
     geom_point()+
     geom_smooth(method="lm")
  """)
```
![image](https://github.com/user-attachments/assets/96e31892-0727-4994-8794-5a68cc670372)

Before yesterday's update, I also got the error you're getting. It's because Mac doesn't like the R plotting event loop to run on a background thread, so in yesterday's update I forced it to run on the main thread.

**Comment by fkgruber** [comment]
yes it works now. For some reason had to rebuild the conda environement.
